spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:postgresql://localhost:5432/fuhosat}
    username: ${JDBC_DATABASE_USERNAME:fuhosat_admin}
    password: ${JDBC_DATABASE_PASSWORD:2222}
    dbcp2:
      max-wait-millis: 30000
      validation-query: SELECT 1
      validation-query-timeout: 30

  security:
    user:
      name: user
      password: password


  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true


springdoc:
  #pathsToMatch: /api/**
  #pathsToMatch: /**
  packagesToScan: com.example.elm
  show-login-endpoint: true
  swagger-ui:
    path: swagger-ui.html


server:
  port: 8089
